services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: searchdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

  redis1:
    image: redis:7
    container_name: redis1
    ports:
      - "6379:6379"

  redis2:
    image: redis:7
    container_name: redis2
    ports:
      - "6380:6379"

  redis3:
    image: redis:7
    container_name: redis3
    ports:
      - "6381:6379"